# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vulnapi < Formula
  desc "Scan your APIs for security vulnerabilities and weaknesses"
  homepage "https://vulnapi.cerberauth.com/"
  version "0.8.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cerberauth/vulnapi/releases/download/v0.8.10/vulnapi_Darwin_x86_64.tar.gz"
      sha256 "a27180dd0e8762eca0f3f8b9bfb92c7ace2c4eba0b09f43e176d7920cefdc01d"

      def install
        bin.install "vulnapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cerberauth/vulnapi/releases/download/v0.8.10/vulnapi_Darwin_arm64.tar.gz"
      sha256 "fcef9d1377a4385825fa3a2ca0a575a84462112eaeb8f5cff738e68cee5d1f68"

      def install
        bin.install "vulnapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cerberauth/vulnapi/releases/download/v0.8.10/vulnapi_Linux_x86_64.tar.gz"
      sha256 "2d9e2464a6d45d26fcd6151f8a8eda0fb47b165f23f8d77a7ee06aa7ebbf9360"
      def install
        bin.install "vulnapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cerberauth/vulnapi/releases/download/v0.8.10/vulnapi_Linux_arm64.tar.gz"
      sha256 "f2a57e74013b2e91e1a13822219187af52e68bb3b652051c5f0c81a3edbae424"
      def install
        bin.install "vulnapi"
      end
    end
  end
end
