FROM gcr.io/distroless/static-debian13:nonroot

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

COPY --chown=nonroot:nonroot ${TARGETOS}/${TARGETARCH}${TARGETVARIANT:+/$TARGETVARIANT}/vulnapi /usr/bin/vulnapi

ENTRYPOINT ["/usr/bin/vulnapi"]
